### ISSUE TITLE
Figure 4 - Control screen for the lab environment?

### ISSUE THREAD

**Issue by yeekangc** [IBM/think2020-cp4a-master-class#4]
The caption for figure 4 reads "Control screen for the lab environment".  Then, the diagram shown is the same as figure 1 i.e. "Microservice architecture for the lab exercise".

Not sure if figure 4 is meant to have a different caption or the figure is meant to be a screen capture of SkyTap control screen?

**Comment by nastacio** [comment]
Good catch, the text had the wrong URL for it.
I just pushed a fix.
